theme: readthedocs
site_url: https://chat.eshop88.cn
site_name: ChatGPT中文文档
nav:
- 阿里云服务器99元/年: https://www.aliyun.com/minisite/goods?userCode=m87ienyv&chat_rtd
- 主页: index.md
- ChatGPT: chatgpt.md
- OpenAI: openai.md
- 官方文档:
  - 介绍: documents/introduction.md
  - 体验: documents/knows.md
- System prompt合集:
  - 中文合集: prompt/system_prompt_cn.md
  - 英文合集: prompt/system_prompt_en.md
  - 特殊风格合集: prompt/system_prompt_other.md
- Hugging Face: 
  - 介绍: huggingface/introduction.md
- 开源大模型:
  - ChatGLM-6B: opensource/ChatGLM2-6B.md
- 中文测试集: testset.md
- 其它GPT:
  - 文心一言: other/wenxin.md
  - 通义千问: other/qianwen.md
  - 天工助手: other/tiangong.md
  - 讯飞星火: other/xinghuo.md
- 应用: 
  - 5movies: application/5movies.md
- 转载:
  - ChatGPT基础科普: transport/basic.md
  - 陆奇：我的大模型世界观: transport/my_llm.md
- 自然语言处理:
  - HanLP: nlp/hanlp.md
- 工具:
  - 尝鲜chatGPT免费好用的梯子: tools/vpn.md
- 关于: about.md
- 公告: notice.md
