theme: readthedocs
site_url: https://chat.eshop88.cn
site_name: ChatGPT中文文档
nav:
- 主页: index.md
- ChatGPT: chatgpt.md
- OpenAI: openai.md
- System prompt合集:
  - 中文合集: prompt/system_prompt_cn.md
  - 英文合集: prompt/system_prompt_en.md
- 应用: 
  - 5movies: application/5movies.md
- 关于: about.md
- 公告: notice.md
