theme: readthedocs
site_url: https://chat.eshop88.cn
site_name: ChatGPT中文文档
nav:
- 主页: index.md
- ChatGPT: chatgpt.md
- OpenAI: openai.md
- 官方文档:
  - 介绍: documents/introduction.md
- System prompt合集:
  - 中文合集: prompt/system_prompt_cn.md
  - 英文合集: prompt/system_prompt_en.md
  - 特殊风格合集: prompt/system_prompt_other.md
- 中文测试集: testset.md
- 其它GPT:
  - 文心一言: other/wenxin.md
- 应用: 
  - 5movies: application/5movies.md
- 关于: about.md
- 公告: notice.md
